### ISSUE TITLE
attribution builder accessible through localhost:8000 not 2424

### ISSUE THREAD

**Issue by julscha** [amzn/oss-attribution-builder#29]
Hi, testing the attribution builder, I ran into the following issue: the builder is only accessible at port 8000 instead of 2424. Could it be that the README/quickstart guide needs to be updated?

**Comment by jpeddicord** [comment]
Whoops -- that's indeed a mistake. 2424 is for the development server, but that's not what's used in the first steps in the README.

**Comment by sschuberth** [comment]
@jpeddicord, could you please elaborate more on the 8080 vs 2424 ports? Under what cirumstances is the "development server" being used, and what for? I'm esp. asking as https://github.com/amzn/oss-attribution-builder/blob/8eda70cb52cda3be21314f6f5aa4d77b7c350548/docs/openapi.yaml#L9 also has port 2424. Is it correct there, or should it also be 8080?

**Comment by jpeddicord** [comment]
@sschuberth 

> also has port 2424. Is it correct there, or should it also be 8000?

The first line there (`  - url: '/api/'`) should work for most cases, including port 8000. The 2424 line is there indeed for the development server, as it technically runs on a different port than webpack-dev-server (which is 2425). Viewing the API docs via webpack-dev-server would route requests to the wrong port otherwise.
